export const CREAR_USUARIO = 'CREAR_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const VERIFICAR_CORREO = 'VERIFICAR_CORREO';
export const ACTUALIZAR_VERIFICAR = 'ACTUALIZAR_VERIFICAR';