export const CREAR_USUARIO = 'CREAR_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const VERIFICAR_CORREO = 'VERIFICAR_CORREO';
export const ACTUALIZAR_VERIFICAR = 'ACTUALIZAR_VERIFICAR';
export const GUARDAR_INFO_USUARIO = 'GUARDAR_INFO_USUARIO';
export const ALERTA_ERROR = 'ALERTA_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

export const TRAER_CHAT = 'TRAER_CHAT';
export const SELECCIONAR_CHAT = 'SELECCIONAR_CHAT';
export const ENVIAR_MENSAJE = 'ENVIAR_MENSAJE';
export const TRAER_CONTACTOS = 'TRAER_CONTACTOS';
export const CONTACTO_ACTUAL = 'CONTACTO_ACTUAL';
export const AGREGAR_NUEVO_MENSAJE = 'AGREGAR_NUEVO_MENSAJE';

//datos
export const OBTENER_DATOS = 'OBTENER_DATOS';
export const AGREGAR_DATO = 'AGREGAR_DATO';
export const ELIMINAR_DATO = 'ELIMINAR_DATO';
export const EDITAR_DATO = 'EDITAR_DATO';
export const CAMBIAR_ESTADO_DATO = 'CAMBIAR_ESTADO_DATO';

//cambiar estado para obtener la notificación
export const TRAER_NOTIFICACION_MENSAJE = 'TRAER_NOTIFICACION_MENSAJE';

// Usuario
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const PASSWORD_EDIT_USER = 'PASSWORD_EDIT_USER';
export const BLOCK_USER = 'BLOCK_USER';
export const ACTUALIZAR_ESTADO_BLOQUEO = 'ACTUALIZAR_ESTADO_BLOQUEO';

// videos
export const OBTENER_VIDEOS = 'OBTENER_VIDEOS';
export const AGREGAR_VIDEO = 'AGREGAR_VIDEO';



